# Generated by Django 4.2.7 on 2023-11-27 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paes', '0002_pao_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('pao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paes.pao')),
            ],
        ),
    ]
